spring:
  application:
    name: image-store

  main:
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Image Store API
    version: 0.0.1-SNAPSHOT
    description: REST API service for storing and retrieving images with metadata and tag-based search

  datasource:
    url: jdbc:h2:file:./data/imagestore
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

imagestore:
  storage:
    type: filesystem  # Options: filesystem, database, s3
    filesystem:
      base-path: ./data/images
    s3:
      bucket: image-store-bucket
      region: us-east-1
      endpoint: # Optional for S3-compatible services

  cache:
    max-age: 31536000  # 1 year in seconds
    enable-etag: true